---
- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - abcde
    - cd-discid
    - flac
    - icedax

- name: Create user
  user:
    name: "{{ abcde_username }}"

- name: Create output directory
  file:
    path: "{{ abcde_output_dir }}"
    state: directory
    mode: 0755
    owner: "{{ abcde_username }}"

- name: Configure abcde
  template:
    src: abcde-flac.conf.j2
    dest: "{{ abcde_home_dir }}/.abcde.conf"

- name: Install abcded script
  copy:
    src: abcded
    dest: /usr/local/bin
    mode: 0755

- name: Install discready script
  copy:
    src: discready
    dest: /usr/local/bin
    mode: 0755

- name: Install abcde service
  template:
    src: abcde.service.j2
    dest: /etc/systemd/system/abcde.service

- name: Restart abcde service
  systemd:
    name: abcde
    daemon_reload: yes
    state: restarted
